function  [output,numTaps] = call_filter_designer_cg(input,mex)

% Extract struct elements so we can call the generated designer which has a
% fixed input requirement

% Fill out necessary fields
input = process_input(input);

% Call function
if mex
    [output,numTaps] = internal_design_filter_cg_mex(...
        input.Rdata,...
        input.Fpass,...
        input.Fstop,...
        input.caldiv,...
        input.FIR,...
        input.HB1,...
        input.PLL_mult,...
        input.Apass,...
        input.Astop,...
        input.phEQ,...
        input.HB2,...
        input.HB3,...
        input.Type,...
        input.RxTx,...
        input.RFbw,...
        input.DAC_div,...
        input.converter_rate,...
        input.PLL_rate,...
        input.Fcenter,...
        input.wnom,...
        input.FIRdBmin,...
        input.int_FIR);
else
    [output,numTaps] = internal_design_filter_cg(...
        input.Rdata,...
        input.Fpass,...
        input.Fstop,...
        input.caldiv,...
        input.FIR,...
        input.HB1,...
        input.PLL_mult,...
        input.Apass,...
        input.Astop,...
        input.phEQ,...
        input.HB2,...
        input.HB3,...
        input.Type,...
        input.RxTx,...
        input.RFbw,...
        input.DAC_div,...
        input.converter_rate,...
        input.PLL_rate,...
        input.Fcenter,...
        input.wnom,...
        input.FIRdBmin,...
        input.int_FIR);
end
