function  [output,numTaps,filterGain,pass,stop] = call_filter_designer_cg(input,mex)

% Extract struct elements so we can call the generated designer which has a
% fixed input requirement

% Fill out necessary fields
input = process_input(input);

if input.HB3 == 2
    hb3 = 2;
elseif input.HB3 == 3
    hb3 = 1;
else
    hb3 = 1;
end
if strcmp(input.RxTx, 'Rx')
    if hb3 == 1
        N = min(16*floor(input.converter_rate/(input.Rdata)),128);
    else
        N = min(16*floor(input.converter_rate/(2*input.Rdata)),128);
    end
else
    switch input.FIR
        case 1
            Nmax = 64;
        case 2
            Nmax = 128;
        case 4
            Nmax = 128;
        otherwise
            error('Wrong FIR Type');
    end
    N = min(16*floor(input.converter_rate*input.DAC_div/(2*input.Rdata)),Nmax);
end

% Call function
if mex
    [output,numTaps,filterGain,pass,stop] = internal_design_filter_cg_mex(...
        input.Rdata,...
        input.Fpass,...
        input.Fstop,...
        input.caldiv,...
        input.FIR,...
        input.HB1,...
        input.PLL_mult,...
        input.Apass,...
        input.Astop,...
        input.phEQ,...
        input.HB2,...
        input.HB3,...
        input.Type,...
        input.RxTx,...
        input.RFbw,...
        input.DAC_div,...
        input.converter_rate,...
        input.PLL_rate,...
        input.Fcenter,...
        input.wnom,...
        input.FIRdBmin,...
        input.int_FIR,...
        N);
else
    [output,numTaps,filterGain,pass,stop] = internal_design_filter_cg(...
        input.Rdata,...
        input.Fpass,...
        input.Fstop,...
        input.caldiv,...
        input.FIR,...
        input.HB1,...
        input.PLL_mult,...
        input.Apass,...
        input.Astop,...
        input.phEQ,...
        input.HB2,...
        input.HB3,...
        input.Type,...
        input.RxTx,...
        input.RFbw,...
        input.DAC_div,...
        input.converter_rate,...
        input.PLL_rate,...
        input.Fcenter,...
        input.wnom,...
        input.FIRdBmin,...
        input.int_FIR,...
        N);
end
