name: Run Tests

on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        matlab-version: ['R2023a', 'R2023b', 'R2024a']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
            release: ${{ matrix.matlab-version }}
            products: DSP_System_Toolbox

      - name: Test Designer
        uses: matlab-actions/run-command@v2
        with:
            command: addpath(genpath('.'));runTests;exit()